### ISSUE TITLE
Test results reporting

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/Icepack#309] opened 2020-03-30 13:31 UTC
This issue probably ought to be in the test results repo's issue list, but I'm afraid it will get lost there.  I'm testing icepack v1.2.1 (and cice v6.1.1) on badger, and noticed a few weirdnesses.

1. Why do badger results not show up on the main v1.2.1 page?
They are here:
https://github.com/CICE-Consortium/Test-Results/wiki/icepack_by_mach
but not here:
https://github.com/CICE-Consortium/Test-Results/wiki/Icepack1.2.1

2.  In the test_output:  one run didn’t finish because of an event on the machine (my fault), so the output for that test listed ‘RUN’ but the summary block at the bottom didn’t catch this.  I only caught it when I uploaded the results and saw the red block on the wiki page (which is now gone, since I re-ran and updated...)

3.  When a re-ran the case and updated the page, the overview table lists 3 separate uploads (which I did, trying to get it right), two of which indicate problems, but apparently they all point to the same results page, which is now all green with no errors.  This is a bit confusing for anyone trying to see what the original errors were.  Not sure if this needs to be fixed, or is just an FYI (maybe for the doc).

4.  The second upload didn't work because I needed to run results.csh in main directory before report_results, after the individual test changed in base_suite.  It's easy enough, I just didn't know to do it.  Maybe it's in the documentation, but if not, let's add it.

**Comment by apcraig** [comment] 2020-03-30 17:48
There are many good points here.  To answer some questions, the release test results are manually created.  I copy/paste to create the release results pages.  I will add badger manually now to the release pages.  There are probably ways the pages could be created automatically for releases, but I'm not sure it's worth the effort to setup the scripts to do that robustly when manually copying and pasting is easy and when this is only needed every few months.

You do have to run results.csh manually before reporting results.  I have intentionally not included running results.csh in report_results because there may be cases where a user wants to edit the results.log file between running results.csh and reporting results, and I want to allow that (although I admit this should be very rare).  If results.log does not exist, report_results will stop.  But if it already exists, but has not been refreshed, that will not be caught.

In terms of reporting results, if you report_results from the same test suite mulitple times, that will create multiple entries on the main table.  I'm a little surprised the detailed results page is overwritten, I can look into that and see if it can be improved.  I will also try to figure out if there is a better way to report tests that time out or are still running in the results.log file to help users avoid reporting results prematurely.  But in general, there are a number of ways to avoid this issue.

- You can manually edit the reported results and remove the older entries in the table.  I sometimes do that.
- You can try to remember not to report results until you are sure you have completed the test suite.
- You can rerun the test suite from scratch.  That will create a new entry and a new detailed report.  You still may want to remove older entries from the table.
- You can just ignore the erroneous entries.  It's unlikely to confuse anyone.

Having said all that, I agree there are some tasks that are worth further investigation

- introduce better reporting of timed out or running tests
- update the detailed reports so every time report_results is called, a unique detailed file is created
- by default, have report_results run results.csh.  add an optional argument in report_results to turn this off.  would this be a better implementation?
- update documentation about reporting results

Anything else we need?  One final point, izumi also struggles with run time outs.  In fact, this [weekend's automated testing was very bad](https://github.com/CICE-Consortium/Test-Results/wiki/cice_by_hash#9040fe2be7146638ced75f36a513b665828db844).  I will probably rerun those today.  I am not convinced a longer run time is the solution.  I think it's often caused by bad nodes or other issues that are not as easy to work around.

**Comment by apcraig** [comment] 2020-03-30 17:55
@eclare108213, I added badger to the Icepack1.2.1 test results.  Have you posted the badger CICE6.1.1 results yet?  I cannot find them.

**Comment by eclare108213** [comment] 2020-03-30 18:08
I haven't tried to post them yet.  The gx3 JRA55 tests failed because I hadn't uploaded the new data files to badger.  I'm trying to do that but bandwidth is a problem, so I might just have to ignore those tests for now.

Regarding your list above:

> - introduce better reporting of timed out or running tests

I think just having 'RUN' results accounted for in the summary at the bottom would be enough.  I didn't look carefully, but in passing _I think_ I noticed that CICE might do this, or at least has more info in that summary block than Icepack does.

> - update the detailed reports so every time report_results is called, a unique detailed file is created

Again, check my work.  What I think is happening and what's really happening might not be the same thing.

> - by default, have report_results run results.csh. add an optional argument in report_results to turn this off. would this be a better implementation?

This might be better, in my opinion.  I'm not sure how valuable it is to not have it update results.csh first.

> - update documentation about reporting results

if/as needed

**Comment by eclare108213** [comment] 2020-03-30 18:27
Here is an example of the summary block and the 'misses' that it isn't reporting.  The clue that they are there is that 129+1 /= 132.

> 128 of 132 tests PASSED
> 0 of 132 tests FAILED
> 1 of 132 tests PENDING
> [eclare@ba-fe1 testsuite.iiso2_1]$ results.csh | grep PEND
> PEND badger_intel_restart_col_1x1_pondlvl test 
> 1 of 132 tests PENDING
> [eclare@ba-fe1 testsuite.iiso2_1]$ results.csh | grep RUN
> RUN  badger_intel_smoke_col_1x1_alt04_debug_run1year run 
> RUN  badger_intel_restart_col_1x1_pondlvl run

**Comment by apcraig** [comment] 2020-04-01 22:55
I am refactoring the test reporting output.  I am proposing something like the following.  The main points are that the "RUN" output is no longer used.  I leave the case in PEND state.  I also have accounted for the results more carefully, adding "MISS" as a counted state and splitting out the different types of failures to improve reporting.  I think this will be helpful.  If I get a fail, I do ./results.csh | grep -i fail to see what is failing.  Now with the breakout, that may not be needed.   Any comments on syntax, content, etc?  In this example, I intentionally tried to generate over existing results which is not allowed to check/demonstrate failures.

```
PASS conrad_intel_smoke_gx3_8x2_diag1_run5day build
PASS conrad_intel_smoke_gx3_8x2_diag1_run5day run 33.45 12.60 6.52
PASS conrad_intel_smoke_gx3_8x2_diag1_run5day test 
FAIL conrad_intel_smoke_gx3_8x2_diag1_run5day generate baseline-already-exists
PASS conrad_intel_smoke_gx3_8x2_diag1_run5day compare cice.5f97e45e23.200322-045057 39.85 14.93 6.83
#---
PASS conrad_intel_smoke_gx3_1x1_diag1_run1day build
PASS conrad_intel_smoke_gx3_1x1_diag1_run1day run 8.42 1.72 4.42
PASS conrad_intel_smoke_gx3_1x1_diag1_run1day test 
FAIL conrad_intel_smoke_gx3_1x1_diag1_run1day generate baseline-already-exists
PASS conrad_intel_smoke_gx3_1x1_diag1_run1day compare cice.5f97e45e23.200322-045057 8.32 1.69 4.42
#---
PASS conrad_intel_restart_gbox128_8x1_diag1 build
#### conrad_intel_restart_gbox128_8x1_diag1 initialrun
PASS conrad_intel_restart_gbox128_8x1_diag1 run 27.64 8.41 13.88
PASS conrad_intel_restart_gbox128_8x1_diag1 test 
FAIL conrad_intel_restart_gbox128_8x1_diag1 generate baseline-already-exists
PASS conrad_intel_restart_gbox128_8x1_diag1 compare cice.5f97e45e23.200322-045057 27.51 8.43 13.89
#---
PASS conrad_intel_restart_gx3_4x2_debug_diag1_run5day build
PEND conrad_intel_restart_gx3_4x2_debug_diag1_run5day run
#### conrad_intel_restart_gx3_4x2_debug_diag1_run5day initialrun
#---
COPY conrad_intel_smoke_gx3_4x1_diag1_run5day_thread build
PASS conrad_intel_smoke_gx3_4x1_diag1_run5day_thread run 15.36 3.01 7.20
PASS conrad_intel_smoke_gx3_4x1_diag1_run5day_thread test 
FAIL conrad_intel_smoke_gx3_4x1_diag1_run5day_thread generate baseline-already-exists
PASS conrad_intel_smoke_gx3_4x1_diag1_run5day_thread compare cice.5f97e45e23.200322-045057 13.91 2.99 7.18
PASS conrad_intel_smoke_gx3_4x1_diag1_run5day_thread bfbcomp conrad_intel_smoke_gx3_8x2_diag1_run5day

Descriptors:
 PASS - successful completion
 COPY - previously compiled code was copied for new test
 MISS - comparison data is missing
 PEND - run has been submitted to queue and is waiting or failed submission
 FAIL - test is still executing, did not complete, or completed and failed

23 total results
23 measured results
18 of 23 tests PASSED
1 of 23 tests PENDING
0 of 23 tests MISSING data
  0 of 4 FAILED build
  0 of 4 FAILED run
  0 of 4 FAILED test
  0 of 4 FAILED compare
  0 of 4 FAILED bfbcomp
  4 of 4 FAILED generate
4 of 23 tests FAILED
```

**Comment by eclare108213** [comment] 2020-04-02 00:39
What does #### mean?  This looks good to me, although PEND and FAIL are a little confusing.  Are the Descriptors accurate?  That says FAIL could indicate a run is still executing, but your comments above sound like that case is now PEND (which makes more sense to me).

**Comment by apcraig** [comment] 2020-04-02 00:47
#### is just a comment.  That is just indicating that the initial run of the restart test completed, but we don't need that.  I'll take it out if it's confusing.  I will also update the descriptors.  More soon.

**Comment by apcraig** [comment] 2020-04-02 02:57
I removed the "runinitial" output.  Now the final bit looks as follows.  Happy to make further changes, just let me know.  thanks!

```
Descriptors:
 PASS - successful completion
 COPY - previously compiled code was copied for new test
 MISS - comparison data is missing
 PEND - status is undertermined; test may still be queued, running, or timed out
 FAIL - test failed

26 measured results of 26 total results
21 of 26 tests PASSED
0 of 26 tests PENDING
0 of 26 tests MISSING data
  0 of 5 FAILED build
  0 of 5 FAILED run
  0 of 5 FAILED test
  0 of 5 FAILED compare
  0 of 5 FAILED bfbcomp
  5 of 5 FAILED generate
5 of 26 tests FAILED
```

**Comment by phil-blain** [comment] 2020-04-02 13:03
Minor thing, but I'd put the breakdown of the failed tests below the `5 of 26 tests FAILED`

**Comment by apcraig** [comment] 2020-04-02 16:49
I originally had a layout with total failed tests above the breakdown.  I also played with indentation a bit.  In the end, I figured the first thing someone wants to know is total failed tests.  So I made that easy to find as the last line.  But I'm happy to switch it again.

The other thing is we could get rid of the detailed breakdown.  I like it and think it will be useful, but maybe that's just me?

**Comment by eclare108213** [comment] 2020-04-02 16:57
I don't mind the detailed breakdown but would probably elect to not have it, if it were just me deciding.  I search the rest of the list to find which ones failed, anyhow, and so having a count only adds a little extra info.  But this might be useful for pasting into PRs?

**Comment by apcraig** [comment] 2020-04-03 17:46
I decided to remove the detailed breakdown from the standard out, but have included it in the results.log file.  I have created a PR in CICE for this.  Will implement the same upgrade in Icepack next.

**Comment by apcraig** [comment] 2020-05-04 18:10
This was addressed in CICE in https://github.com/CICE-Consortium/CICE/pull/428.  I think the proposed updates are complete.  I will close.

**Closed by apcraig** 2020-05-04 18:10 UTC
Labels: Priority: Low, Testing, Tools
