### ISSUE TITLE
timeseries plots in conda environment

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/Icepack#404] opened 2022-10-07 22:09 UTC
I'm not sure if this is a problem with my particular conda setup, but it would be nice to have gnuplot (or some equivalent) available for use with the timeseries.csh script (which I copied from configuration/scripts/tests into my local test directory).

`$ ./timeseries.csh logs/ice_diag.full_ITD.221007-155537`
`Plotting data for 'area fraction' and saving to logs/ice_diag.full_ITD.221007-155537_area_fraction.png`
`gnuplot: Command not found.`

**Comment by phil-blain** [comment] 2022-10-11 13:03
Hi @eclare108213, in CICE we now have a Python version of this script that gets copied into `$ICE_CASEDIR` along with the gnuplot version. Maybe this is just a matter of adding that Python script to the Icepack repo?

**Comment by dabail10** [comment] 2024-02-23 18:14
Adding @apcraig to this as well.

**Comment by dabail10** [comment] 2024-02-26 17:24
> Hi @eclare108213, in CICE we now have a Python version of this script that gets copied into `$ICE_CASEDIR` along with the gnuplot version. Maybe this is just a matter of adding that Python script to the Icepack repo?

The issue is that the python timeseries script is configured for the full CICE log output (e.g. total ice area for NH and SH). I think the gnuplot version is the way to go. I am looking into a way to install gnuplot on my Mac.

**Comment by anton-seaice** [comment] 2024-02-26 22:00
> The issue is that the python timeseries script is configured for the full CICE log output (e.g. total ice area for NH and SH). I think the gnuplot version is the way to go. I am looking into a way to install gnuplot on my Mac.

You should just be able to add   `- gnuplot` as another line in `environment.yml` and run `$ conda env update`

I do agree though that moving to a python version would be easier to modify / maintain going forward.

**Comment by dabail10** [comment] 2024-02-26 22:33
I tried a pip install gnuplot and it did not find it.

**Comment by anton-seaice** [comment] 2024-02-26 22:37
> I tried a pip install gnuplot and it did not find it.

Yeah correct - pip is for python and gnuplot is an executable / not python

**Comment by dabail10** [comment] 2024-02-26 22:38
Got it! The conda install works.

**Comment by dabail10** [comment] 2024-02-26 22:40
Ok.  As @anton-seaice suggests, we can add gnuplot to the conda environment. Then at least we will have something for the tutorial.

**Comment by eclare108213** [comment] 2024-04-04 18:27
I am testing out the homework instructions and ran into this issue.  `- gnuplot` is in my new clone's environment.yml file under `# Plotting dependencies`, but I'm getting an error `gnuplot: Command not found.` and the .png files are all empty.  The conda environment is activated. Help?

**Comment by eclare108213** [comment] 2024-04-04 18:34
Never mind - I thought the conda environment was activated, but only for 'base', not 'icepack'.

**Comment by apcraig** [comment] 2024-05-23 20:56
This has been fixed, gnuplot is now part of the icepack conda env as of March 1, 2024, #483

**Closed by apcraig** 2024-05-23 20:56 UTC
Labels: Scripts, Analysis
